// <auto-generated />
namespace Anewluv.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class profiledata_profileidremoveal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profiledata_profileidremoveal));
        
        string IMigrationMetadata.Id
        {
            get { return "201504030047562_profiledata_profileidremoveal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
