//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misc.ErrorLoggingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomErrorLog", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.ErrorLoggingService.lu_Application))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.ErrorLoggingService.lu_logSeverity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.ErrorLoggingService.LogSeverityEnum))]
    public partial class CustomErrorLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misc.ErrorLoggingService.lu_Application ApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssemblyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misc.ErrorLoggingService.lu_logSeverity LogSeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object LoggedObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoggedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentMethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StacktraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int application_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int logseverity_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misc.ErrorLoggingService.lu_Application Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName {
            get {
                return this.AssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssemblyNameField, value) != true)) {
                    this.AssemblyNameField = value;
                    this.RaisePropertyChanged("AssemblyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorPage {
            get {
                return this.ErrorPageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorPageField, value) != true)) {
                    this.ErrorPageField = value;
                    this.RaisePropertyChanged("ErrorPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumbers {
            get {
                return this.LineNumbersField;
            }
            set {
                if ((this.LineNumbersField.Equals(value) != true)) {
                    this.LineNumbersField = value;
                    this.RaisePropertyChanged("LineNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misc.ErrorLoggingService.lu_logSeverity LogSeverity {
            get {
                return this.LogSeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.LogSeverityField, value) != true)) {
                    this.LogSeverityField = value;
                    this.RaisePropertyChanged("LogSeverity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object LoggedObject {
            get {
                return this.LoggedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedObjectField, value) != true)) {
                    this.LoggedObjectField = value;
                    this.RaisePropertyChanged("LoggedObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoggedUser {
            get {
                return this.LoggedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedUserField, value) != true)) {
                    this.LoggedUserField = value;
                    this.RaisePropertyChanged("LoggedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentMethodName {
            get {
                return this.ParentMethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentMethodNameField, value) != true)) {
                    this.ParentMethodNameField = value;
                    this.RaisePropertyChanged("ParentMethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileIDField, value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString {
            get {
                return this.QueryStringField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryStringField, value) != true)) {
                    this.QueryStringField = value;
                    this.RaisePropertyChanged("QueryString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sessionid {
            get {
                return this.SessionidField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionidField, value) != true)) {
                    this.SessionidField = value;
                    this.RaisePropertyChanged("Sessionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stacktrace {
            get {
                return this.StacktraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StacktraceField, value) != true)) {
                    this.StacktraceField = value;
                    this.RaisePropertyChanged("Stacktrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int application_id {
            get {
                return this.application_idField;
            }
            set {
                if ((this.application_idField.Equals(value) != true)) {
                    this.application_idField = value;
                    this.RaisePropertyChanged("application_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logseverity_id {
            get {
                return this.logseverity_idField;
            }
            set {
                if ((this.logseverity_idField.Equals(value) != true)) {
                    this.logseverity_idField = value;
                    this.RaisePropertyChanged("logseverity_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lu_Application", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    public partial class lu_Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lu_logSeverity", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    public partial class lu_logSeverity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogSeverityEnum", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    public enum LogSeverityEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CriticalError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxSeverity = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLoggingService.IErrorLoggingService")]
    public interface IErrorLoggingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLoggingService/GetData", ReplyAction="http://tempuri.org/IErrorLoggingService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLoggingService/WriteCompleteLogEntry", ReplyAction="http://tempuri.org/IErrorLoggingService/WriteCompleteLogEntryResponse")]
        int WriteCompleteLogEntry(Misc.ErrorLoggingService.CustomErrorLog logEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLoggingService/TranslateLogSeverity", ReplyAction="http://tempuri.org/IErrorLoggingService/TranslateLogSeverityResponse")]
        int TranslateLogSeverity(Misc.ErrorLoggingService.LogSeverityEnum LogSeverityValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLoggingServiceChannel : Misc.ErrorLoggingService.IErrorLoggingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLoggingServiceClient : System.ServiceModel.ClientBase<Misc.ErrorLoggingService.IErrorLoggingService>, Misc.ErrorLoggingService.IErrorLoggingService {
        
        public ErrorLoggingServiceClient() {
        }
        
        public ErrorLoggingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLoggingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLoggingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLoggingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public int WriteCompleteLogEntry(Misc.ErrorLoggingService.CustomErrorLog logEntry) {
            return base.Channel.WriteCompleteLogEntry(logEntry);
        }
        
        public int TranslateLogSeverity(Misc.ErrorLoggingService.LogSeverityEnum LogSeverityValue) {
            return base.Channel.TranslateLogSeverity(LogSeverityValue);
        }
    }
}
