// <auto-generated />
namespace Nmedia.Infrastructure.Domain.Apikey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class renamedkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201501100526273_renamedkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
