// <auto-generated />
namespace Nmedia.Infrastructure.Domain.Apikey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class newest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newest));
        
        string IMigrationMetadata.Id
        {
            get { return "201501100242566_newest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
