//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misc.PhotoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnewluvResponse", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Services.Contracts.ServiceResp" +
        "onse")]
    [System.SerializableAttribute()]
    public partial class AnewluvResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Misc.PhotoService.Document> DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Misc.PhotoService.ResponseMessage> ResponseMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Shell.MVC2.Domain.Entities.Anewluv.profilestatusEnum currentstatuscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime currentstatusdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profileid1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profileid2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Shell.MVC2.Domain.Entities.Anewluv.profilestatusEnum profilestatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime profilestatusdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool requestreturnflagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime responsecreatedateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Misc.PhotoService.Document> Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Misc.PhotoService.ResponseMessage> ResponseMessages {
            get {
                return this.ResponseMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessagesField, value) != true)) {
                    this.ResponseMessagesField = value;
                    this.RaisePropertyChanged("ResponseMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shell.MVC2.Domain.Entities.Anewluv.profilestatusEnum currentstatuscode {
            get {
                return this.currentstatuscodeField;
            }
            set {
                if ((this.currentstatuscodeField.Equals(value) != true)) {
                    this.currentstatuscodeField = value;
                    this.RaisePropertyChanged("currentstatuscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime currentstatusdate {
            get {
                return this.currentstatusdateField;
            }
            set {
                if ((this.currentstatusdateField.Equals(value) != true)) {
                    this.currentstatusdateField = value;
                    this.RaisePropertyChanged("currentstatusdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profileid1 {
            get {
                return this.profileid1Field;
            }
            set {
                if ((object.ReferenceEquals(this.profileid1Field, value) != true)) {
                    this.profileid1Field = value;
                    this.RaisePropertyChanged("profileid1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profileid2 {
            get {
                return this.profileid2Field;
            }
            set {
                if ((object.ReferenceEquals(this.profileid2Field, value) != true)) {
                    this.profileid2Field = value;
                    this.RaisePropertyChanged("profileid2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shell.MVC2.Domain.Entities.Anewluv.profilestatusEnum profilestatus {
            get {
                return this.profilestatusField;
            }
            set {
                if ((this.profilestatusField.Equals(value) != true)) {
                    this.profilestatusField = value;
                    this.RaisePropertyChanged("profilestatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime profilestatusdate {
            get {
                return this.profilestatusdateField;
            }
            set {
                if ((this.profilestatusdateField.Equals(value) != true)) {
                    this.profilestatusdateField = value;
                    this.RaisePropertyChanged("profilestatusdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool requestreturnflag {
            get {
                return this.requestreturnflagField;
            }
            set {
                if ((this.requestreturnflagField.Equals(value) != true)) {
                    this.requestreturnflagField = value;
                    this.RaisePropertyChanged("requestreturnflag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime responsecreatedate {
            get {
                return this.responsecreatedateField;
            }
            set {
                if ((this.responsecreatedateField.Equals(value) != true)) {
                    this.responsecreatedateField = value;
                    this.RaisePropertyChanged("responsecreatedate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Services.Contracts.ServiceResp" +
        "onse")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] documentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misc.PhotoService.DocumentTypes documenttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mimetypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] document {
            get {
                return this.documentField;
            }
            set {
                if ((object.ReferenceEquals(this.documentField, value) != true)) {
                    this.documentField = value;
                    this.RaisePropertyChanged("document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misc.PhotoService.DocumentTypes documenttype {
            get {
                return this.documenttypeField;
            }
            set {
                if ((this.documenttypeField.Equals(value) != true)) {
                    this.documenttypeField = value;
                    this.RaisePropertyChanged("documenttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((object.ReferenceEquals(this.filenameField, value) != true)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.mimetypeField, value) != true)) {
                    this.mimetypeField = value;
                    this.RaisePropertyChanged("mimetype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Services.Contracts.ServiceResp" +
        "onse")]
    [System.SerializableAttribute()]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataelementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errormessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataelement {
            get {
                return this.dataelementField;
            }
            set {
                if ((object.ReferenceEquals(this.dataelementField, value) != true)) {
                    this.dataelementField = value;
                    this.RaisePropertyChanged("dataelement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errormessageField, value) != true)) {
                    this.errormessageField = value;
                    this.RaisePropertyChanged("errormessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypes", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Services.Contracts.ServiceResp" +
        "onse")]
    public enum DocumentTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Photo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhotoService.IPhotoService")]
    public interface IPhotoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getphotomodelbyphotoid", ReplyAction="http://tempuri.org/IPhotoService/getphotomodelbyphotoidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel getphotomodelbyphotoid(string photoid, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getphotomodelbyprofileid", ReplyAction="http://tempuri.org/IPhotoService/getphotomodelbyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel getphotomodelbyprofileid(string profileid, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getphotomodelsbyprofileidandstatus", ReplyAction="http://tempuri.org/IPhotoService/getphotomodelsbyprofileidandstatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel> getphotomodelsbyprofileidandstatus(string profileid, string status, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getpagedphotomodelbyprofileidandstatus", ReplyAction="http://tempuri.org/IPhotoService/getpagedphotomodelbyprofileidandstatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel> getpagedphotomodelbyprofileidandstatus(string profileid, string status, string format, string page, string pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getpagedphotoviewmodelbyprofileid", ReplyAction="http://tempuri.org/IPhotoService/getpagedphotoviewmodelbyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoViewModel getpagedphotoviewmodelbyprofileid(string profileid, string format, string page, string pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getphotoeditmodelbyphotoid", ReplyAction="http://tempuri.org/IPhotoService/getphotoeditmodelbyphotoidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel getphotoeditmodelbyphotoid(string photoid, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getphotoeditmodelsbyprofileidandstatus", ReplyAction="http://tempuri.org/IPhotoService/getphotoeditmodelsbyprofileidandstatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel> getphotoeditmodelsbyprofileidandstatus(string profileid, string status, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getpagedphotoeditmodelsbyprofileidstatus", ReplyAction="http://tempuri.org/IPhotoService/getpagedphotoeditmodelsbyprofileidstatusResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel> getpagedphotoeditmodelsbyprofileidstatus(string profileid, string status, string format, string page, string pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getpagededitphotoviewmodelbyprofileidandformat", ReplyAction="http://tempuri.org/IPhotoService/getpagededitphotoviewmodelbyprofileidandformatRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoEditViewModel getpagededitphotoviewmodelbyprofileidandformat(string profileid, string format, string page, string pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/deleteuserphoto", ReplyAction="http://tempuri.org/IPhotoService/deleteuserphotoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Misc.PhotoService.AnewluvResponse deleteuserphoto(string photoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/makeuserphoto_private", ReplyAction="http://tempuri.org/IPhotoService/makeuserphoto_privateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Misc.PhotoService.AnewluvResponse makeuserphoto_private(string photoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/makeuserphoto_public", ReplyAction="http://tempuri.org/IPhotoService/makeuserphoto_publicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Misc.PhotoService.AnewluvResponse makeuserphoto_public(string photoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/addphotos", ReplyAction="http://tempuri.org/IPhotoService/addphotosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Misc.PhotoService.AnewluvResponse addphotos(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/addsinglephoto", ReplyAction="http://tempuri.org/IPhotoService/addsinglephotoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Misc.PhotoService.AnewluvResponse addsinglephoto(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadModel newphoto, string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/checkvalidjpggif", ReplyAction="http://tempuri.org/IPhotoService/checkvalidjpggifResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool checkvalidjpggif(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getgalleryphotobyscreenname", ReplyAction="http://tempuri.org/IPhotoService/getgalleryphotobyscreennameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        string getgalleryphotobyscreenname(string screenname, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getgalleryimagebyphotoid", ReplyAction="http://tempuri.org/IPhotoService/getgalleryimagebyphotoidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        string getgalleryimagebyphotoid(string photoid, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getgalleryphotobyprofileid", ReplyAction="http://tempuri.org/IPhotoService/getgalleryphotobyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        string getgalleryphotobyprofileid(string profileid, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getgalleryimagebynormalizedscreenname", ReplyAction="http://tempuri.org/IPhotoService/getgalleryimagebynormalizedscreennameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        string getgalleryimagebynormalizedscreenname(string screenname, string format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/checkifphotocaptionalreadyexists", ReplyAction="http://tempuri.org/IPhotoService/checkifphotocaptionalreadyexistsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool checkifphotocaptionalreadyexists(string profileid, string photocaption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/checkforgalleryphotobyprofileid", ReplyAction="http://tempuri.org/IPhotoService/checkforgalleryphotobyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool checkforgalleryphotobyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/checkforuploadedphotobyprofileid", ReplyAction="http://tempuri.org/IPhotoService/checkforuploadedphotobyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool checkforuploadedphotobyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/getimagebytesfromurl", ReplyAction="http://tempuri.org/IPhotoService/getimagebytesfromurlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.PhotoService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        string getimagebytesfromurl(string imageUrl, string source);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhotoServiceChannel : Misc.PhotoService.IPhotoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotoServiceClient : System.ServiceModel.ClientBase<Misc.PhotoService.IPhotoService>, Misc.PhotoService.IPhotoService {
        
        public PhotoServiceClient() {
        }
        
        public PhotoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel getphotomodelbyphotoid(string photoid, string format) {
            return base.Channel.getphotomodelbyphotoid(photoid, format);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel getphotomodelbyprofileid(string profileid, string format) {
            return base.Channel.getphotomodelbyprofileid(profileid, format);
        }
        
        public System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel> getphotomodelsbyprofileidandstatus(string profileid, string status, string format) {
            return base.Channel.getphotomodelsbyprofileidandstatus(profileid, status, format);
        }
        
        public System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel> getpagedphotomodelbyprofileidandstatus(string profileid, string status, string format, string page, string pagesize) {
            return base.Channel.getpagedphotomodelbyprofileidandstatus(profileid, status, format, page, pagesize);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoViewModel getpagedphotoviewmodelbyprofileid(string profileid, string format, string page, string pagesize) {
            return base.Channel.getpagedphotoviewmodelbyprofileid(profileid, format, page, pagesize);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel getphotoeditmodelbyphotoid(string photoid, string format) {
            return base.Channel.getphotoeditmodelbyphotoid(photoid, format);
        }
        
        public System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel> getphotoeditmodelsbyprofileidandstatus(string profileid, string status, string format) {
            return base.Channel.getphotoeditmodelsbyprofileidandstatus(profileid, status, format);
        }
        
        public System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel> getpagedphotoeditmodelsbyprofileidstatus(string profileid, string status, string format, string page, string pagesize) {
            return base.Channel.getpagedphotoeditmodelsbyprofileidstatus(profileid, status, format, page, pagesize);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoEditViewModel getpagededitphotoviewmodelbyprofileidandformat(string profileid, string format, string page, string pagesize) {
            return base.Channel.getpagededitphotoviewmodelbyprofileidandformat(profileid, format, page, pagesize);
        }
        
        public Misc.PhotoService.AnewluvResponse deleteuserphoto(string photoid) {
            return base.Channel.deleteuserphoto(photoid);
        }
        
        public Misc.PhotoService.AnewluvResponse makeuserphoto_private(string photoid) {
            return base.Channel.makeuserphoto_private(photoid);
        }
        
        public Misc.PhotoService.AnewluvResponse makeuserphoto_public(string photoid) {
            return base.Channel.makeuserphoto_public(photoid);
        }
        
        public Misc.PhotoService.AnewluvResponse addphotos(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadViewModel model) {
            return base.Channel.addphotos(model);
        }
        
        public Misc.PhotoService.AnewluvResponse addsinglephoto(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadModel newphoto, string profileid) {
            return base.Channel.addsinglephoto(newphoto, profileid);
        }
        
        public bool checkvalidjpggif(byte[] image) {
            return base.Channel.checkvalidjpggif(image);
        }
        
        public string getgalleryphotobyscreenname(string screenname, string format) {
            return base.Channel.getgalleryphotobyscreenname(screenname, format);
        }
        
        public string getgalleryimagebyphotoid(string photoid, string format) {
            return base.Channel.getgalleryimagebyphotoid(photoid, format);
        }
        
        public string getgalleryphotobyprofileid(string profileid, string format) {
            return base.Channel.getgalleryphotobyprofileid(profileid, format);
        }
        
        public string getgalleryimagebynormalizedscreenname(string screenname, string format) {
            return base.Channel.getgalleryimagebynormalizedscreenname(screenname, format);
        }
        
        public bool checkifphotocaptionalreadyexists(string profileid, string photocaption) {
            return base.Channel.checkifphotocaptionalreadyexists(profileid, photocaption);
        }
        
        public bool checkforgalleryphotobyprofileid(string profileid) {
            return base.Channel.checkforgalleryphotobyprofileid(profileid);
        }
        
        public bool checkforuploadedphotobyprofileid(string profileid) {
            return base.Channel.checkforuploadedphotobyprofileid(profileid);
        }
        
        public string getimagebytesfromurl(string imageUrl, string source) {
            return base.Channel.getimagebytesfromurl(imageUrl, source);
        }
    }
}
