// <auto-generated />
namespace Nmedia.Infrastructure.Domain.NotificationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class fixedaddressmessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedaddressmessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201311220536015_fixedaddressmessages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
