//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.MVC2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.MVC2.Resources.EmailMessageResources", typeof(EmailMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;http://www.AnewLuv.com/Account/ActivateProfile/?ProfileId={0}&amp;ActivationCode={1}&quot;&gt;Activate Your Profile By Clicking this Link&lt;/a&gt;.
        /// </summary>
        internal static string ActivationURL {
            get {
                return ResourceManager.GetString("ActivationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ola.lawal@gmail.com,anewluvadmin@nmedia.com.
        /// </summary>
        internal static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ola.lawal@gmail.com,welaworks@mail.com,anewluvadmin@nmedia.com.
        /// </summary>
        internal static string AdminEmailPhotos {
            get {
                return ResourceManager.GetString("AdminEmailPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator@nmedia.com.
        /// </summary>
        internal static string AminEmail2 {
            get {
                return ResourceManager.GetString("AminEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoNotReply@AnewLuv.com.
        /// </summary>
        internal static string DefaultEmailSender {
            get {
                return ResourceManager.GetString("DefaultEmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support@Anewluv.com,anewluvhelp@mail.com,ola_lawal@yahoo.com.
        /// </summary>
        internal static string DefaultSupportEmail {
            get {
                return ResourceManager.GetString("DefaultSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnewLuv.com *Your Photo has been uploaded *.
        /// </summary>
        internal static string PhotoUploadedMessageSubject {
            get {
                return ResourceManager.GetString("PhotoUploadedMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string SendEmails {
            get {
                return ResourceManager.GetString("SendEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was blocked on Anewluv.com by {0}.
        /// </summary>
        internal static string SpamBlockedAdminMessageSubject {
            get {
                return ResourceManager.GetString("SpamBlockedAdminMessageSubject", resourceCulture);
            }
        }
    }
}
