//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misc.InfoNotificationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomErrorLog", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.InfoNotificationService.templateenum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.InfoNotificationService.ServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.lu_photoformat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.lu_photoImagersizerformat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.profile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.lu_securityquestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.visiblitysetting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.visiblitysettings_country>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.visiblitysettings_country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.visiblitysettings_gender>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.visiblitysettings_gender))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.lu_gender))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.photorejectionreasonEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.ContactUsModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.MemberSearchViewModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.MemberSearchViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.MembersViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.AccountModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoEditViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.PhotoUploadModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.photoeditmodel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.quicksearchmodel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.registermodel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.rpxprofile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LogonViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LogOnModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LostAccountInfoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LostActivationCodeModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.InfoNotificationService.lu_Application))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misc.InfoNotificationService.lu_logSeverity))]
    public partial class CustomErrorLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misc.InfoNotificationService.lu_Application ApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssemblyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misc.InfoNotificationService.lu_logSeverity LogSeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object LoggedObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoggedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentMethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StacktraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int application_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int logseverity_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misc.InfoNotificationService.lu_Application Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName {
            get {
                return this.AssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssemblyNameField, value) != true)) {
                    this.AssemblyNameField = value;
                    this.RaisePropertyChanged("AssemblyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorPage {
            get {
                return this.ErrorPageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorPageField, value) != true)) {
                    this.ErrorPageField = value;
                    this.RaisePropertyChanged("ErrorPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumbers {
            get {
                return this.LineNumbersField;
            }
            set {
                if ((this.LineNumbersField.Equals(value) != true)) {
                    this.LineNumbersField = value;
                    this.RaisePropertyChanged("LineNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misc.InfoNotificationService.lu_logSeverity LogSeverity {
            get {
                return this.LogSeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.LogSeverityField, value) != true)) {
                    this.LogSeverityField = value;
                    this.RaisePropertyChanged("LogSeverity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object LoggedObject {
            get {
                return this.LoggedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedObjectField, value) != true)) {
                    this.LoggedObjectField = value;
                    this.RaisePropertyChanged("LoggedObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoggedUser {
            get {
                return this.LoggedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedUserField, value) != true)) {
                    this.LoggedUserField = value;
                    this.RaisePropertyChanged("LoggedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentMethodName {
            get {
                return this.ParentMethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentMethodNameField, value) != true)) {
                    this.ParentMethodNameField = value;
                    this.RaisePropertyChanged("ParentMethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileIDField, value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString {
            get {
                return this.QueryStringField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryStringField, value) != true)) {
                    this.QueryStringField = value;
                    this.RaisePropertyChanged("QueryString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sessionid {
            get {
                return this.SessionidField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionidField, value) != true)) {
                    this.SessionidField = value;
                    this.RaisePropertyChanged("Sessionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stacktrace {
            get {
                return this.StacktraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StacktraceField, value) != true)) {
                    this.StacktraceField = value;
                    this.RaisePropertyChanged("Stacktrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int application_id {
            get {
                return this.application_idField;
            }
            set {
                if ((this.application_idField.Equals(value) != true)) {
                    this.application_idField = value;
                    this.RaisePropertyChanged("application_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logseverity_id {
            get {
                return this.logseverity_idField;
            }
            set {
                if ((this.logseverity_idField.Equals(value) != true)) {
                    this.logseverity_idField = value;
                    this.RaisePropertyChanged("logseverity_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lu_Application", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    public partial class lu_Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lu_logSeverity", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Custom" +
        "ErrorLogModel")]
    [System.SerializableAttribute()]
    public partial class lu_logSeverity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="templateenum", Namespace="http://schemas.datacontract.org/2004/07/Shell.MVC2.Infrastructure.Entities.Notifi" +
        "cationModel")]
    public enum templateenum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenericErrorMessage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberContactUsMemberMesage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberContactUsAdminMessage = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberCreatedMemberNotification = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberCreatedAdminNotification = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberCreatedJianRainOrOPenIDMemberNotification = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberCreatedJainRanOrOpenIDAdminNotification = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPasswordChangeMemberNotification = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPasswordChangedAdminNotification = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActivatedMemberNotification = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActivatedAdminNotification = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActivationCodeRecoveredMemberNotification = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActivationCodeRecoveredAdminNotification = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedEmailMessageMemberNotification = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedEmailMessageAdminNotification = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedPeekMemberNotification = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedPeekAdminNotification = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedLikeMemberNotification = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedLikeAdminNotification = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedInterestMemberNotification = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedInterestAdminNotification = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedChatRequestMemberNotification = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedChatRequestAdminNotification = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedOfflineChatMessageMemberNotification = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberRecivedOfflineChatMessageAdminNotification = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPhotoRejectedMemberNotification = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPhotoRejectedAdminNotification = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPhotoUploadedMemberNotification = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberPhotoUploadedAdminNotification = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberMatchesSentMemberNotification = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberMatchestSentAdminNotificaton = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberSpamBlockedAdminNotification = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberFriendRequestRecivedMemberNotification = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberFriendRequestRecivedAdminNotification = 36,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InfoNotificationService.IInfoNotificationService")]
    public interface IInfoNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/senderrormessage", ReplyAction="http://tempuri.org/IInfoNotificationService/senderrormessageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailModel senderrormessage(Misc.InfoNotificationService.CustomErrorLog error, string addresstype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendcontactusemail", ReplyAction="http://tempuri.org/IInfoNotificationService/sendcontactusemailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendcontactusemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.ContactUsModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmembercreatedemail", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmembercreatedemailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmembercreatedemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.registermodel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmembercreatedopenidemail", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmembercreatedopenidemailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmembercreatedopenidemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.registermodel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberpasswordchangedemail", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberpasswordchangedemailRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberpasswordchangedemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LogonViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberprofileactivatedemailbyprof" +
            "ileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberprofileactivatedemailbyprof" +
            "ileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberprofileactivatedemailbyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberactivationcoderecoveredemai" +
            "lbyprofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberactivationcoderecoveredemai" +
            "lbyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberactivationcoderecoveredemailbyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberemailmemssagereceivedemailb" +
            "yprofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberemailmemssagereceivedemailb" +
            "yprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberemailmemssagereceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberpeekreceivedemailbyprofilei" +
            "d", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberpeekreceivedemailbyprofilei" +
            "dResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberpeekreceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberlikereceivedemailbyprofilei" +
            "d", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberlikereceivedemailbyprofilei" +
            "dResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberlikereceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberinterestreceivedemailbyprof" +
            "ileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberinterestreceivedemailbyprof" +
            "ileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberinterestreceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberchatrequestreceivedemailbyp" +
            "rofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberchatrequestreceivedemailbyp" +
            "rofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberchatrequestreceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberofflinechatmessagereceivede" +
            "mailbyprofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberofflinechatmessagereceivede" +
            "mailbyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberofflinechatmessagereceivedemailbyprofileid(string recipientprofileid, string senderprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberphotorejectedemailbyprofile" +
            "id", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberphotorejectedemailbyprofile" +
            "idResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberphotorejectedemailbyprofileid(string profileid, string adminprofileid, Shell.MVC2.Domain.Entities.Anewluv.photorejectionreasonEnum reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendmemberphotouploadedemailbyprofile" +
            "id", ReplyAction="http://tempuri.org/IInfoNotificationService/sendmemberphotouploadedemailbyprofile" +
            "idResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberphotouploadedemailbyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendadminspamblockedemailbyprofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendadminspamblockedemailbyprofileidR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminspamblockedemailbyprofileid(string blockedprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendemailmatchesemailbyprofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendemailmatchesemailbyprofileidRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendemailmatchesemailbyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendadminmemberspamblockedemailbyprof" +
            "ileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendadminmemberspamblockedemailbyprof" +
            "ileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberspamblockedemailbyprofileid(string spamblockedprofileid, string reason, string blockedby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendadminmemberblockedemailbyprofilei" +
            "d", ReplyAction="http://tempuri.org/IInfoNotificationService/sendadminmemberblockedemailbyprofilei" +
            "dResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberblockedemailbyprofileid(string blockedprofileid, string blockerprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/sendadminmemberphotoapprovedemailbypr" +
            "ofileid", ReplyAction="http://tempuri.org/IInfoNotificationService/sendadminmemberphotoapprovedemailbypr" +
            "ofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberphotoapprovedemailbyprofileid(string approvedprofileid, string adminprofileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoNotificationService/getemailbytemplateid", ReplyAction="http://tempuri.org/IInfoNotificationService/getemailbytemplateidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Misc.InfoNotificationService.ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailModel getemailbytemplateid(Misc.InfoNotificationService.templateenum template);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInfoNotificationServiceChannel : Misc.InfoNotificationService.IInfoNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoNotificationServiceClient : System.ServiceModel.ClientBase<Misc.InfoNotificationService.IInfoNotificationService>, Misc.InfoNotificationService.IInfoNotificationService {
        
        public InfoNotificationServiceClient() {
        }
        
        public InfoNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailModel senderrormessage(Misc.InfoNotificationService.CustomErrorLog error, string addresstype) {
            return base.Channel.senderrormessage(error, addresstype);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendcontactusemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.ContactUsModel model) {
            return base.Channel.sendcontactusemail(model);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmembercreatedemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.registermodel model) {
            return base.Channel.sendmembercreatedemail(model);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmembercreatedopenidemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.registermodel model) {
            return base.Channel.sendmembercreatedopenidemail(model);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberpasswordchangedemail(Shell.MVC2.Domain.Entities.Anewluv.ViewModels.LogonViewModel model) {
            return base.Channel.sendmemberpasswordchangedemail(model);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberprofileactivatedemailbyprofileid(string profileid) {
            return base.Channel.sendmemberprofileactivatedemailbyprofileid(profileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberactivationcoderecoveredemailbyprofileid(string profileid) {
            return base.Channel.sendmemberactivationcoderecoveredemailbyprofileid(profileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberemailmemssagereceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberemailmemssagereceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberpeekreceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberpeekreceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberlikereceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberlikereceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberinterestreceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberinterestreceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberchatrequestreceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberchatrequestreceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberofflinechatmessagereceivedemailbyprofileid(string recipientprofileid, string senderprofileid) {
            return base.Channel.sendmemberofflinechatmessagereceivedemailbyprofileid(recipientprofileid, senderprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberphotorejectedemailbyprofileid(string profileid, string adminprofileid, Shell.MVC2.Domain.Entities.Anewluv.photorejectionreasonEnum reason) {
            return base.Channel.sendmemberphotorejectedemailbyprofileid(profileid, adminprofileid, reason);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendmemberphotouploadedemailbyprofileid(string profileid) {
            return base.Channel.sendmemberphotouploadedemailbyprofileid(profileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminspamblockedemailbyprofileid(string blockedprofileid) {
            return base.Channel.sendadminspamblockedemailbyprofileid(blockedprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendemailmatchesemailbyprofileid(string profileid) {
            return base.Channel.sendemailmatchesemailbyprofileid(profileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberspamblockedemailbyprofileid(string spamblockedprofileid, string reason, string blockedby) {
            return base.Channel.sendadminmemberspamblockedemailbyprofileid(spamblockedprofileid, reason, blockedby);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberblockedemailbyprofileid(string blockedprofileid, string blockerprofileid) {
            return base.Channel.sendadminmemberblockedemailbyprofileid(blockedprofileid, blockerprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailViewModel sendadminmemberphotoapprovedemailbyprofileid(string approvedprofileid, string adminprofileid) {
            return base.Channel.sendadminmemberphotoapprovedemailbyprofileid(approvedprofileid, adminprofileid);
        }
        
        public Shell.MVC2.Domain.Entities.Anewluv.ViewModels.Email.EmailModel getemailbytemplateid(Misc.InfoNotificationService.templateenum template) {
            return base.Channel.getemailbytemplateid(template);
        }
    }
}
