using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;

namespace Shell.MVC2.Domain.Entities.Anewluv
{
    public partial class AnewluvContext : DbContext
    {

        public DbSet<application> applications { get; set; }
        public DbSet<applicationitem > applicationitems { get; set; }
       public DbSet<applicationrole> applicationrole { get; set; } //generated by fluent API
        public DbSet<applicationiconconversion> applicationiconconversion { get; set; }

        public DbSet<lu_applicationitempaymenttype> lu_applicationitempaymenttype { get; set; }
        public DbSet<lu_applicationitemtransfertype> lu_applicationitemtransfertype { get; set; }
        public DbSet<lu_applicationtype> lu_applicationtype { get; set; }
        public DbSet<lu_iconformat> lu_iconformat { get; set; }
        public DbSet<lu_iconImagersizerformat> lu_iconImagersizerformat { get; set; }

    }
}
