//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anewluv.Lib.MembersMapperService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MembersMapperService.IMembersMapperService")]
    public interface IMembersMapperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/mapmembersearchviewmodel", ReplyAction="http://tempuri.org/IMembersMapperService/mapmembersearchviewmodelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MemberSearchViewModel mapmembersearchviewmodel(string viewerprofileid, Anewluv.Domain.Data.ViewModels.MemberSearchViewModel modeltomap, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/mapmembersearchviewmodels", ReplyAction="http://tempuri.org/IMembersMapperService/mapmembersearchviewmodelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> mapmembersearchviewmodels(string viewerprofileid, System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> modelstomap, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getmembersearchviewmodel", ReplyAction="http://tempuri.org/IMembersMapperService/getmembersearchviewmodelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MemberSearchViewModel getmembersearchviewmodel(string viewerprofileid, string profileid, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getmembersearchviewmodels", ReplyAction="http://tempuri.org/IMembersMapperService/getmembersearchviewmodelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getmembersearchviewmodels(string viewerprofileid, System.Collections.Generic.List<int> profileids, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getprofilebrowsemodel", ReplyAction="http://tempuri.org/IMembersMapperService/getprofilebrowsemodelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.ProfileBrowseModel getprofilebrowsemodel(string viewerprofileid, string profileid, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getprofilebrowsemodels", ReplyAction="http://tempuri.org/IMembersMapperService/getprofilebrowsemodelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.ProfileBrowseModel> getprofilebrowsemodels(string viewerprofileid, System.Collections.Generic.List<int> profileids, string allphotos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getprofilecriteriamodel", ReplyAction="http://tempuri.org/IMembersMapperService/getprofilecriteriamodelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.ProfileCriteriaModel getprofilecriteriamodel(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getprofilecriteriamodelempty", ReplyAction="http://tempuri.org/IMembersMapperService/getprofilecriteriamodelemptyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.ProfileCriteriaModel getprofilecriteriamodelempty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getdefaultquicksearchsettingsmembers", ReplyAction="http://tempuri.org/IMembersMapperService/getdefaultquicksearchsettingsmembersResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel getdefaultquicksearchsettingsmembers(Anewluv.Domain.Data.ViewModels.ProfileModel Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getdefaultsearchsettingsguest", ReplyAction="http://tempuri.org/IMembersMapperService/getdefaultsearchsettingsguestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel getdefaultsearchsettingsguest(Anewluv.Domain.Data.ViewModels.ProfileModel Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getregistermodel", ReplyAction="http://tempuri.org/IMembersMapperService/getregistermodelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.registermodel getregistermodel(Anewluv.Domain.Data.ViewModels.MembersViewModel membersmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getregistermodelopenid", ReplyAction="http://tempuri.org/IMembersMapperService/getregistermodelopenidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.registermodel getregistermodelopenid(Anewluv.Domain.Data.ViewModels.MembersViewModel membersmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getregistermodeltest", ReplyAction="http://tempuri.org/IMembersMapperService/getregistermodeltestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.registermodel getregistermodeltest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/updatememberdata", ReplyAction="http://tempuri.org/IMembersMapperService/updatememberdataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel updatememberdata(Anewluv.Domain.Data.ViewModels.MembersViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/updatememberdatabyprofileid", ReplyAction="http://tempuri.org/IMembersMapperService/updatememberdatabyprofileidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel updatememberdatabyprofileid(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/updateguestdata", ReplyAction="http://tempuri.org/IMembersMapperService/updateguestdataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool updateguestdata(Anewluv.Domain.Data.ViewModels.MembersViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/removeguestdata", ReplyAction="http://tempuri.org/IMembersMapperService/removeguestdataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        bool removeguestdata(string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getguestdata", ReplyAction="http://tempuri.org/IMembersMapperService/getguestdataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel getguestdata(string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getmemberdata", ReplyAction="http://tempuri.org/IMembersMapperService/getmemberdataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel getmemberdata(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/mapmember", ReplyAction="http://tempuri.org/IMembersMapperService/mapmemberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel mapmember(string profileid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/mapguest", ReplyAction="http://tempuri.org/IMembersMapperService/mapguestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        Anewluv.Domain.Data.ViewModels.MembersViewModel mapguest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getquickmatches", ReplyAction="http://tempuri.org/IMembersMapperService/getquickmatchesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getquickmatches(Anewluv.Domain.Data.ViewModels.ProfileModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembersMapperService/getemailmatches", ReplyAction="http://tempuri.org/IMembersMapperService/getemailmatchesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFault), Action="http://Schemas.Testws.Medtox.com", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getemailmatches(Anewluv.Domain.Data.ViewModels.ProfileModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembersMapperServiceChannel : Anewluv.Lib.MembersMapperService.IMembersMapperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembersMapperServiceClient : System.ServiceModel.ClientBase<Anewluv.Lib.MembersMapperService.IMembersMapperService>, Anewluv.Lib.MembersMapperService.IMembersMapperService {
        
        public MembersMapperServiceClient() {
        }
        
        public MembersMapperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembersMapperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembersMapperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembersMapperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Anewluv.Domain.Data.ViewModels.MemberSearchViewModel mapmembersearchviewmodel(string viewerprofileid, Anewluv.Domain.Data.ViewModels.MemberSearchViewModel modeltomap, string allphotos) {
            return base.Channel.mapmembersearchviewmodel(viewerprofileid, modeltomap, allphotos);
        }
        
        public System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> mapmembersearchviewmodels(string viewerprofileid, System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> modelstomap, string allphotos) {
            return base.Channel.mapmembersearchviewmodels(viewerprofileid, modelstomap, allphotos);
        }
        
        public Anewluv.Domain.Data.ViewModels.MemberSearchViewModel getmembersearchviewmodel(string viewerprofileid, string profileid, string allphotos) {
            return base.Channel.getmembersearchviewmodel(viewerprofileid, profileid, allphotos);
        }
        
        public System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getmembersearchviewmodels(string viewerprofileid, System.Collections.Generic.List<int> profileids, string allphotos) {
            return base.Channel.getmembersearchviewmodels(viewerprofileid, profileids, allphotos);
        }
        
        public Anewluv.Domain.Data.ViewModels.ProfileBrowseModel getprofilebrowsemodel(string viewerprofileid, string profileid, string allphotos) {
            return base.Channel.getprofilebrowsemodel(viewerprofileid, profileid, allphotos);
        }
        
        public System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.ProfileBrowseModel> getprofilebrowsemodels(string viewerprofileid, System.Collections.Generic.List<int> profileids, string allphotos) {
            return base.Channel.getprofilebrowsemodels(viewerprofileid, profileids, allphotos);
        }
        
        public Anewluv.Domain.Data.ViewModels.ProfileCriteriaModel getprofilecriteriamodel(string profileid) {
            return base.Channel.getprofilecriteriamodel(profileid);
        }
        
        public Anewluv.Domain.Data.ViewModels.ProfileCriteriaModel getprofilecriteriamodelempty() {
            return base.Channel.getprofilecriteriamodelempty();
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel getdefaultquicksearchsettingsmembers(Anewluv.Domain.Data.ViewModels.ProfileModel Model) {
            return base.Channel.getdefaultquicksearchsettingsmembers(Model);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel getdefaultsearchsettingsguest(Anewluv.Domain.Data.ViewModels.ProfileModel Model) {
            return base.Channel.getdefaultsearchsettingsguest(Model);
        }
        
        public Anewluv.Domain.Data.ViewModels.registermodel getregistermodel(Anewluv.Domain.Data.ViewModels.MembersViewModel membersmodel) {
            return base.Channel.getregistermodel(membersmodel);
        }
        
        public Anewluv.Domain.Data.ViewModels.registermodel getregistermodelopenid(Anewluv.Domain.Data.ViewModels.MembersViewModel membersmodel) {
            return base.Channel.getregistermodelopenid(membersmodel);
        }
        
        public Anewluv.Domain.Data.ViewModels.registermodel getregistermodeltest() {
            return base.Channel.getregistermodeltest();
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel updatememberdata(Anewluv.Domain.Data.ViewModels.MembersViewModel model) {
            return base.Channel.updatememberdata(model);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel updatememberdatabyprofileid(string profileid) {
            return base.Channel.updatememberdatabyprofileid(profileid);
        }
        
        public bool updateguestdata(Anewluv.Domain.Data.ViewModels.MembersViewModel model) {
            return base.Channel.updateguestdata(model);
        }
        
        public bool removeguestdata(string sessionid) {
            return base.Channel.removeguestdata(sessionid);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel getguestdata(string sessionid) {
            return base.Channel.getguestdata(sessionid);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel getmemberdata(string profileid) {
            return base.Channel.getmemberdata(profileid);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel mapmember(string profileid) {
            return base.Channel.mapmember(profileid);
        }
        
        public Anewluv.Domain.Data.ViewModels.MembersViewModel mapguest() {
            return base.Channel.mapguest();
        }
        
        public System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getquickmatches(Anewluv.Domain.Data.ViewModels.ProfileModel model) {
            return base.Channel.getquickmatches(model);
        }
        
        public System.Collections.Generic.List<Anewluv.Domain.Data.ViewModels.MemberSearchViewModel> getemailmatches(Anewluv.Domain.Data.ViewModels.ProfileModel model) {
            return base.Channel.getemailmatches(model);
        }
    }
}
