// <auto-generated />
namespace Nmedia.Infrastructure.Domain.Notification.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfromaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfromaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201701260751475_addedfromaddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
